# The workflow to check master after push.
name: Master checks after push
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        java-version: [ 11, 17 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}
      - name: Build with Gradle
        run: ./gradlew build
