# The workflow to check pull requests into master.
# This checks the source in the state as if after the merge.
name: Pull request checks
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        java-version: [ 11, 17 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build with Gradle
        run: ./gradlew build
